name: Build docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv and sync dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --all-extras

    - name: Build Sphinx documentation
      run: |
        cd docs
        uv run make html

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build ./docs/ --tag adernild/rorclient-docs:latest
        docker push adernild/rorclient-docs:latest
